# Generated by Django 6.0.5 on 2026-07-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('highlighted_text', models.CharField(blank=True, max_length=80, verbose_name='متن رنگی داخل عنوان')),
                ('subtitle', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_slides/', verbose_name='عکس بنر')),
                ('badge_text', models.CharField(default='Driving Theory MVP', max_length=80, verbose_name='متن Badge')),
                ('badge_icon', models.CharField(default='🚗', max_length=10, verbose_name='آیکون Badge')),
                ('primary_button_text', models.CharField(default='شروع', max_length=60, verbose_name='متن دکمه اصلی')),
                ('primary_button_link', models.CharField(default='/', max_length=255, verbose_name='لینک دکمه اصلی')),
                ('secondary_button_text', models.CharField(blank=True, max_length=60, verbose_name='متن دکمه دوم')),
                ('secondary_button_link', models.CharField(blank=True, max_length=255, verbose_name='لینک دکمه دوم')),
                ('preview_icon', models.CharField(default='🚗', max_length=10, verbose_name='آیکون کارت سمت چپ')),
                ('preview_title', models.CharField(blank=True, max_length=100, verbose_name='عنوان کارت سمت چپ')),
                ('preview_text', models.CharField(blank=True, max_length=180, verbose_name='متن کارت سمت چپ')),
                ('color', models.CharField(choices=[('red', 'قرمز'), ('blue', 'آبی'), ('green', 'سبز'), ('purple', 'بنفش')], default='red', max_length=20, verbose_name='رنگ اسلاید')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اسلاید صفحه اصلی',
                'verbose_name_plural': 'اسلایدهای صفحه اصلی',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
