# Generated by Django 6.0.5 on 2026-07-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='badge_text_de',
            field=models.CharField(default='Driving Theory MVP', max_length=80, null=True, verbose_name='متن Badge'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='badge_text_en',
            field=models.CharField(default='Driving Theory MVP', max_length=80, null=True, verbose_name='متن Badge'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='badge_text_fa',
            field=models.CharField(default='Driving Theory MVP', max_length=80, null=True, verbose_name='متن Badge'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='highlighted_text_de',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='متن رنگی داخل عنوان'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='highlighted_text_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='متن رنگی داخل عنوان'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='highlighted_text_fa',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='متن رنگی داخل عنوان'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='preview_text_de',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='متن کارت سمت چپ'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='preview_text_en',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='متن کارت سمت چپ'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='preview_text_fa',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='متن کارت سمت چپ'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='preview_title_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان کارت سمت چپ'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='preview_title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان کارت سمت چپ'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='preview_title_fa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان کارت سمت چپ'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='primary_button_text_de',
            field=models.CharField(default='شروع', max_length=60, null=True, verbose_name='متن دکمه اصلی'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='primary_button_text_en',
            field=models.CharField(default='شروع', max_length=60, null=True, verbose_name='متن دکمه اصلی'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='primary_button_text_fa',
            field=models.CharField(default='شروع', max_length=60, null=True, verbose_name='متن دکمه اصلی'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_button_text_de',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='متن دکمه دوم'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_button_text_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='متن دکمه دوم'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_button_text_fa',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='متن دکمه دوم'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_de',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_de',
            field=models.CharField(max_length=120, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_fa',
            field=models.CharField(max_length=120, null=True, verbose_name='عنوان'),
        ),
    ]
