# Generated by Django 6.0.5 on 2026-05-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['section', '-created_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveSmallIntegerField(default=3, help_text='Fehlerpunkte / امتیاز خطا'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('basic', 'Basic Knowledge'), ('class_b', 'Class B')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
