# Generated by Django 6.0.5 on 2026-05-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_options_question_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_video_replays',
            field=models.PositiveSmallIntegerField(default=4, help_text='Maximum allowed video views before answering'),
        ),
    ]
