# Generated by Django 6.0.5 on 2026-05-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_examsession_examanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.CharField(blank=True, default='', help_text='For multiple correct answers, use comma format: 1,2,4', max_length=20),
        ),
    ]
