# Generated by Django 6.0.5 on 2026-05-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_correct_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='selected_answers',
            field=models.CharField(blank=True, default='', help_text='Selected answers for multiple choice, e.g. 1,2,4', max_length=20),
        ),
    ]
