# Generated by Django 6.0.5 on 2026-05-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_examanswer_selected_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_1_translation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_2_translation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_3_translation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_4_translation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='title_translation',
            field=models.TextField(blank=True, help_text='Persian translation of the question'),
        ),
    ]
