# Generated by Django 6.0.5 on 2026-06-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_favoritequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='mode',
            field=models.CharField(choices=[('practice', 'Practice'), ('read', 'Read'), ('test', 'Test')], default='test', max_length=20),
        ),
    ]
