# Generated by Django 6.0.5 on 2026-06-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_examsession_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scenario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='scenario_translation',
            field=models.TextField(blank=True),
        ),
    ]
