# Generated by Django 6.0.5 on 2026-06-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_question_scenario_question_scenario_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quiz.quizcategory'),
        ),
    ]
