# Generated by Django 6.0.5 on 2026-06-07 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_quizcategory_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Main Category',
                'verbose_name_plural': 'Main Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quiz.quizcategory',),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quiz.quizcategory',),
        ),
        migrations.AlterModelOptions(
            name='quizcategory',
            options={'ordering': ['parent__name', 'name'], 'verbose_name': 'Quiz Category', 'verbose_name_plural': 'Quiz Categories'},
        ),
        migrations.AddField(
            model_name='question',
            name='main_category',
            field=models.ForeignKey(blank=True, help_text='Main parent category, e.g. مواد مخدر or هفتاد آزمون اصلی', limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_questions', to='quiz.quizcategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='Child category, e.g. هروئین or آزمون 1', limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_questions', to='quiz.quizcategory'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.quizcategory'),
        ),
    ]
