# Generated by Django 6.0.5 on 2026-07-23 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_question_explanation_de_question_explanation_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examanswer',
            options={'verbose_name': 'پاسخ آزمون', 'verbose_name_plural': 'پاسخ\u200cهای آزمون'},
        ),
        migrations.AlterModelOptions(
            name='examsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'جلسه آزمون', 'verbose_name_plural': 'جلسه\u200cهای آزمون'},
        ),
        migrations.AlterModelOptions(
            name='favoritequestion',
            options={'verbose_name': 'سؤال موردعلاقه', 'verbose_name_plural': 'سؤال\u200cهای موردعلاقه'},
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'دسته\u200cبندی اصلی', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای اصلی'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['section', '-created_at'], 'verbose_name': 'سؤال', 'verbose_name_plural': 'سؤال\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='quizcategory',
            options={'ordering': ['parent__name', 'name'], 'verbose_name': 'دسته\u200cبندی سؤال', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای سؤال'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'زیردسته', 'verbose_name_plural': 'زیردسته\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='wrongquestion',
            options={'verbose_name': 'سؤال اشتباه', 'verbose_name_plural': 'سؤال\u200cهای اشتباه'},
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان پاسخ'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.examsession', verbose_name='آزمون'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='صحیح است'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to='quiz.question', verbose_name='سؤال'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='selected_answer',
            field=models.PositiveSmallIntegerField(verbose_name='پاسخ انتخاب\u200cشده'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='selected_answers',
            field=models.CharField(blank=True, default='', help_text='برای چند پاسخ انتخابی، شماره\u200cها را با ویرگول وارد کنید؛ مانند 1,2,4', max_length=20, verbose_name='پاسخ\u200cهای انتخاب\u200cشده'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='پایان یافته'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='mode',
            field=models.CharField(choices=[('practice', 'تمرین'), ('read', 'مطالعه'), ('test', 'آزمون')], default='test', max_length=20, verbose_name='حالت'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='exam_sessions', to='quiz.question', verbose_name='سؤال\u200cها'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='favoritequestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='favoritequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='سؤال'),
        ),
        migrations.AlterField(
            model_name='favoritequestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.quizcategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.PositiveSmallIntegerField(choices=[(1, 'گزینه ۱'), (2, 'گزینه ۲'), (3, 'گزینه ۳'), (4, 'گزینه ۴')], verbose_name='پاسخ صحیح'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answers',
            field=models.CharField(blank=True, default='', help_text='برای چند پاسخ صحیح، شماره\u200cها را با ویرگول وارد کنید؛ مانند 1,2,4', max_length=20, verbose_name='پاسخ\u200cهای صحیح'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='توضیح پاسخ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation_de',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح پاسخ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح پاسخ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح پاسخ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='منتشر شده'),
        ),
        migrations.AlterField(
            model_name='question',
            name='main_category',
            field=models.ForeignKey(blank=True, help_text='دسته\u200cبندی والد اصلی را انتخاب کنید؛ برای مثال مواد مخدر یا هفتاد آزمون اصلی.', limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_questions', to='quiz.quizcategory', verbose_name='دسته\u200cبندی اصلی'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_video_replays',
            field=models.PositiveSmallIntegerField(default=4, help_text='حداکثر تعداد دفعات مجاز مشاهده ویدیو پیش از پاسخ\u200cدادن', verbose_name='حداکثر دفعات پخش ویدیو'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_1',
            field=models.CharField(max_length=255, verbose_name='گزینه ۱'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_1_de',
            field=models.CharField(max_length=255, null=True, verbose_name='گزینه ۱'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_1_en',
            field=models.CharField(max_length=255, null=True, verbose_name='گزینه ۱'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_1_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='گزینه ۱'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_1_translation',
            field=models.CharField(blank=True, max_length=255, verbose_name='ترجمه گزینه ۱'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2',
            field=models.CharField(max_length=255, verbose_name='گزینه ۲'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2_de',
            field=models.CharField(max_length=255, null=True, verbose_name='گزینه ۲'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2_en',
            field=models.CharField(max_length=255, null=True, verbose_name='گزینه ۲'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='گزینه ۲'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2_translation',
            field=models.CharField(blank=True, max_length=255, verbose_name='ترجمه گزینه ۲'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.CharField(max_length=255, verbose_name='گزینه ۳'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3_de',
            field=models.CharField(max_length=255, null=True, verbose_name='گزینه ۳'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3_en',
            field=models.CharField(max_length=255, null=True, verbose_name='گزینه ۳'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='گزینه ۳'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3_translation',
            field=models.CharField(blank=True, max_length=255, verbose_name='ترجمه گزینه ۳'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='گزینه ۴'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='گزینه ۴'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='گزینه ۴'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='گزینه ۴'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4_translation',
            field=models.CharField(blank=True, max_length=255, verbose_name='ترجمه گزینه ۴'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveSmallIntegerField(default=3, help_text='Fehlerpunkte / امتیاز خطا', verbose_name='امتیاز خطا'),
        ),
        migrations.AlterField(
            model_name='question',
            name='scenario',
            field=models.TextField(blank=True, verbose_name='سناریو'),
        ),
        migrations.AlterField(
            model_name='question',
            name='scenario_de',
            field=models.TextField(blank=True, null=True, verbose_name='سناریو'),
        ),
        migrations.AlterField(
            model_name='question',
            name='scenario_en',
            field=models.TextField(blank=True, null=True, verbose_name='سناریو'),
        ),
        migrations.AlterField(
            model_name='question',
            name='scenario_fa',
            field=models.TextField(blank=True, null=True, verbose_name='سناریو'),
        ),
        migrations.AlterField(
            model_name='question',
            name='scenario_translation',
            field=models.TextField(blank=True, verbose_name='ترجمه سناریو'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('basic', 'دانش پایه'), ('class_b', 'کلاس B')], default='basic', max_length=20, verbose_name='بخش'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='زیرمجموعه را انتخاب کنید؛ برای مثال هروئین یا آزمون ۱.', limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_questions', to='quiz.quizcategory', verbose_name='زیرمجموعه'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(verbose_name='متن سؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_de',
            field=models.TextField(null=True, verbose_name='متن سؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_en',
            field=models.TextField(null=True, verbose_name='متن سؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_fa',
            field=models.TextField(null=True, verbose_name='متن سؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_translation',
            field=models.TextField(blank=True, help_text='ترجمه فارسی سؤال', verbose_name='ترجمه سؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='نشانی ویدیو'),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quiz.quizcategory', verbose_name='دسته\u200cبندی والد'),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='سؤال'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
